import Navbar from '@/components/Navbar';
import './globals.css';
import { Open_Sans } from 'next/font/google';
import AuthContext from '../context/AuthContext';
import ReactQueryContext from '../context/ReactQueryContext';
const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko' className={openSans.className}>
      <body className='w-full bg-neutral-50'>
        <AuthContext>
          <ReactQueryContext>
            <header className='sticky top-0 border-b z-20'>
              <div className='max-w-screen-xl mx-auto'>
                <Navbar />
              </div>
            </header>
            <main className='w-full flex justify-center max-w-screen-xl mx-auto'>
              {children}
            </main>
          </ReactQueryContext>
        </AuthContext>
        <div id='portal'></div>
      </body>
    </html>
  );
}
